replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

zookeeper:
  connect: localhost:2181
  sessionTimeoutMillis: 5000
  connectTimeoutMillis: 15000
  retryMillis: 5000
  maxRetries: 2147483647

kafka:
  brokerConnect: localhost:9092

jvm:
  opts: ""

nameOverride: ""
fullnameOverride: ""

server:
  servlet:
    contextPath: /

service:
  type: NodePort
  port: 9000
  nodePort: 30900

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
