replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: localhost:9092
  properties: ""
  truststore: ""
  keystore: ""
  properties_file: ""
  truststore_file: ""
  keystore_file: ""

host:

jvm:
  opts: ""
jmx:
  port: 

nameOverride: ""
fullnameOverride: ""

server:
  port: 
  servlet:
    contextPath: /

service:
  type: NodePort
  port: 9000
  nodePort: 30900

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}